# Generated by Django 3.1.7 on 2021-03-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0004_auto_20210319_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='item',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceDetail',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
