# Generated by Django 3.1.7 on 2021-03-20 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0007_auto_20210320_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
    ]
