# Generated by Django 3.1.7 on 2021-03-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0008_remove_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
