# Generated by Django 3.1.7 on 2021-03-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0020_auto_20210322_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='payment_option',
            field=models.CharField(choices=[('S', 'Stripe'), ('P', 'Paypal')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
