# Generated by Django 3.1.7 on 2021-03-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0023_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='boot',
            field=models.CharField(choices=[('warning', 'warning'), ('danger', 'danger')], default='danger', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('NEW', 'NEW'), ('HOT', 'HOT')], max_length=10),
        ),
    ]
